#!/usr/bin/env bash
# Tek jpg mynd, fjarlægi bakgrunn, kantsker og breyti síðan í png
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

convert $script_dir/images/Clarin_B-Centre.jpg -crop +10+12 -crop -8-8 $script_dir/images/Clarin_B-Centre.png
bg=$(convert $script_dir/images/Clarin_B-Centre.png -format "%[pixel:p{0,0}]" info:)
convert $script_dir/images/Clarin_B-Centre.png -resize 176 -fuzz 20% -transparent "$bg" $script_dir/images/clarinb-centre.png
rm $script_dir/images/Clarin_B-Centre.png

